USE [riskadjustment]
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HCPCSRXC]') AND type in (N'U'))
DROP TABLE [dbo].[HCPCSRXC]
GO
/****** Object:  Table [dbo].[HCPCSRXC]    Script Date: 8/28/2023 9:04:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HCPCSRXC](
	[HCPCS_CODE] [nvarchar](50) NOT NULL,
	[RXC] [nvarchar](10) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1324','1')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J3485','1')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('C9482','3')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0282','3')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1742','3')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1815','6')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1817','6')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0202','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1595','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1826','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1830','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J2350','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('Q3028','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0129','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0135','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0490','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0717','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1438','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1602','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1745','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J3262','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J3358','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J3380','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('Q5103','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('Q5104','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J7639','10')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J7682','10')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1160','3')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0881','4')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0885','4')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0887','4')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J2501','4')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1746','1')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J9302','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('C9077','1')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0741','1')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('C9086','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('Q5121','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0491','9')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0283','3')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('C9149','7')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1961','1')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J1814','6')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J9381','7')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J2329','8')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0739','ACF_01')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0750','ACF_01')
INSERT [dbo].[HCPCSRXC] ([HCPCS_CODE], [RXC]) VALUES ('J0751','ACF_01')
GO
